spring:
  application:
    name: thinking-in-spring-security
  datasource:
    url: jdbc:mysql://localhost:3306/security?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.qq.com  # 邮箱服务器
    port: 587
    username: 778671998@qq.com
# 配置 JSP 的视图解析器
logging:
  level:
    org.springframework.security: trace